FROM python:3.9.9-slim-buster

# set directory
WORKDIR /home

COPY ./requirements.txt .

RUN apt-get update && apt-get upgrade -y \
    && pip install -r requirements.txt

# choose port
EXPOSE 8501

CMD ["streamlit", "run", "src/temperature-frontend.py"]